# Generated by Django 5.2.1 on 2025-06-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
