# Generated by Django 5.2.1 on 2025-06-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_price_book_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/defaul.jgp', upload_to='books'),
        ),
    ]
